/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leonardo.gym.view;

import com.leonardo.gym.dao.DetallesRutinasDao;
import com.leonardo.gym.dao.EjerciciosDao;
import com.leonardo.gym.dao.MusculoDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public final class Ejercicios extends javax.swing.JDialog {

    /**
     * Creates new form Ejercicios
     */
    //abcdef
    DetallesRutinasDao deta=new DetallesRutinasDao();
    Rutinas rut=new Rutinas();
    EjerciciosDao ejer=new EjerciciosDao();
    MusculoDao musc=new MusculoDao();
    ResultSet rsEjer,rsMusc,tabla;
    String id_musc="1",desc;
    
    public Ejercicios(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
       
         AñadirDatosMusculo();
     
       
  
    }

    public void AñadirDatosEjercicio() {
         jcbEjercicio.removeAllItems();
         
        switch (jcbMusculo.getSelectedIndex()) {
            case 0:
                id_musc="1";
                break;
                  case 1:
                id_musc="2";
                break;
                  case 2:
                id_musc="3";
                break;
                  case 3:
                id_musc="4";
                break;
                  case 4:
                id_musc="5";
                break;  
            default:
                System.out.println(id_musc);
        }
        
        
        
         rsEjer=ejer.AñadirEjercicios(id_musc);
        
          try {

            while (rsEjer.next()) {
                
               
                jcbEjercicio.addItem(rsEjer.getString("id_ejercicio")+"-"+rsEjer.getString("nombre"));
              
            }
            rsEjer.close();
    } catch (SQLException ex) {
            Logger.getLogger(RutinaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
}
    
    }
    
      public void AñadirDatosMusculo() {
         rsMusc=musc.AñadirMusculo();
        
          try {

            while (rsMusc.next()) {
               
                jcbMusculo.addItem(rsMusc.getString("nombre"));
            }
            rsMusc.close();
    } catch (SQLException ex) {
            Logger.getLogger(RutinaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
}
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEjercicio = new javax.swing.JLabel();
        lblMusculo = new javax.swing.JLabel();
        jcbMusculo = new javax.swing.JComboBox();
        jcbEjercicio = new javax.swing.JComboBox();
        lblSeries = new javax.swing.JLabel();
        lblDescanso = new javax.swing.JLabel();
        txtSeries = new javax.swing.JTextField();
        txtDescanso = new javax.swing.JTextField();
        lblRepeticiones = new javax.swing.JLabel();
        txtRepeticiones = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblEjercicio.setText("Ejercicio");

        lblMusculo.setText("Musculo");

        jcbMusculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMusculoActionPerformed(evt);
            }
        });

        jcbEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEjercicioActionPerformed(evt);
            }
        });

        lblSeries.setText("Series");

        lblDescanso.setText("Descanso");

        lblRepeticiones.setText("Repeticiones");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEjercicio)
                    .addComponent(lblMusculo))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnGuardar)
                        .addGap(75, 75, 75)
                        .addComponent(btnCerrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbMusculo, 0, 179, Short.MAX_VALUE)
                            .addComponent(jcbEjercicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescanso)
                            .addComponent(lblSeries))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescanso))
                        .addGap(34, 34, 34)
                        .addComponent(lblRepeticiones)
                        .addGap(31, 31, 31)
                        .addComponent(txtRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescanso)
                        .addComponent(txtDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbMusculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeries)
                            .addComponent(txtSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRepeticiones)
                            .addComponent(lblMusculo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEjercicio)
                            .addComponent(jcbEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCerrar))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbMusculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMusculoActionPerformed

           AñadirDatosEjercicio();      
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMusculoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    //String id_rutina=rut.getTxtId_Rutina();
       
        deta.insertarRutina("1", jcbEjercicio.getSelectedItem().toString().substring(0, 2), txtRepeticiones.getText(),txtDescanso.getText() ,txtSeries.getText() );
        
       String nombre=jcbEjercicio.getSelectedItem().toString().substring(4, 15);
        tabla=deta.ConsultarDetallesRutinas("1");
         

            try {
                while (tabla.next()) {
                    
                     desc=tabla.getString(6);
                }
                 rut.actualizarTablaRutinas(jcbEjercicio.getSelectedItem().toString().substring(0, 2),nombre ,desc, txtRepeticiones.getText(),txtDescanso.getText() ,txtSeries.getText() );
       
           
            } catch (SQLException ex) {
                Logger.getLogger(Ejercicios.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        dispose();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jcbEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEjercicioActionPerformed

        

// TODO add your handling code here:
    }//GEN-LAST:event_jcbEjercicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Ejercicios dialog = new Ejercicios(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcbEjercicio;
    private javax.swing.JComboBox jcbMusculo;
    private javax.swing.JLabel lblDescanso;
    private javax.swing.JLabel lblEjercicio;
    private javax.swing.JLabel lblMusculo;
    private javax.swing.JLabel lblRepeticiones;
    private javax.swing.JLabel lblSeries;
    private javax.swing.JTextField txtDescanso;
    private javax.swing.JTextField txtRepeticiones;
    private javax.swing.JTextField txtSeries;
    // End of variables declaration//GEN-END:variables
}
