/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leonardo.gym.view;

import com.leonardo.gym.dao.DetallesRutinasDao;
import com.leonardo.gym.dao.EjerciciosDao;
import com.leonardo.gym.dao.RutinasDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javy
 */
public class Rutinas extends javax.swing.JDialog {

    /**
     * Creates new form Rutinas
     */
    EjerciciosDao ejercicio = new EjerciciosDao();
    RutinasDao detalle = new RutinasDao();
    DetallesRutinasDao detalleRutina = new DetallesRutinasDao();
    RutinaPrincipal rutinap;
    Ejercicios ejercicios;
    ResultSet rs;
    DefaultTableModel modelo;
    ResultSet rstabla, tablaEjer;
    boolean esInsercion = false;

    public boolean isEsInsercion() {
        return esInsercion;
    }

    public void setEsInsercion(boolean esInsercion) {
        this.esInsercion = esInsercion;
    }

    public Rutinas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        rutinap = (RutinaPrincipal) parent;
        initComponents();
        modelo = (DefaultTableModel) jtbEjercicios.getModel();
        establecerId_Rutina();

        txtId_cliente.setText(rutinap.getTxtId_Cliente());

    }

    public Rutinas() {
        
        

    }

     public String getTxtId_Rutina(){
        return txtId_Rutina.getText();
    }
    public void establecerId_Rutina() {

        String id_cliente = rutinap.getTxtId_Cliente();
        rs = detalle.ConsultarId(id_cliente);

        try {

            while (rs.next()) {

                txtId_Rutina.setText(rs.getString("id_rutina"));
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(RutinaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void LimpiarTabla() {
      
        for (int i = 0; jtbEjercicios.getRowCount() > i; i++) {
            modelo.removeRow(i);
            i -= i;
        }
    }

    public void rellenarDatosTabla() {
        //LimpiarTabla();
        rstabla = detalleRutina.ConsultarDetallesRutinas(txtId_Rutina.getText());
            
        try {

            while (rstabla.next()) {

                modelo.addRow(new Object[]{rstabla.getInt("id_ejercicio"), rstabla.getString("nombre"),
                    rstabla.getString("descripcion"), rstabla.getInt("nseries"), rstabla.getInt("repeticiones"), rstabla.getInt("descansos")});

            }
            
            
            if (!rstabla.last()) {
                JOptionPane.showMessageDialog(null, "No se encontraron ejercicios con esos datos");
            }
        } catch (SQLException ex) {
            Logger.getLogger(BusquedaPane.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId_Rutina = new javax.swing.JTextField();
        lblId_Rutina = new javax.swing.JLabel();
        lblFecha_Inicio = new javax.swing.JLabel();
        txtFecha_Inicio = new javax.swing.JTextField();
        lblFecha_Final = new javax.swing.JLabel();
        txtFecha_Final = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEjercicios = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId_cliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtId_Rutina.setEditable(false);

        lblId_Rutina.setText("Id_Rutina");

        lblFecha_Inicio.setText("Fecha inicio");

        lblFecha_Final.setText("Fecha final");

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir.png"))); // NOI18N
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jtbEjercicios.setAutoCreateRowSorter(true);
        jtbEjercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "nº series", "Repeticiones", "Descansos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbEjercicios);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Id_cliente");

        txtId_cliente.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFecha_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFecha_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId_Rutina)
                                .addGap(64, 64, 64)
                                .addComponent(txtId_Rutina, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha_Final, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha_Final, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(txtId_cliente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnGuardar)
                        .addGap(116, 116, 116)
                        .addComponent(btnCerrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId_Rutina)
                    .addComponent(txtId_Rutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtId_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha_Inicio)
                    .addComponent(txtFecha_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha_Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha_Final))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCerrar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed

        ejercicios= new Ejercicios(this, true);
        ejercicios.setId_rutina(getTxtId_Rutina());
        ejercicios.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirActionPerformed
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int fila = jtbEjercicios.getSelectedRow();

        DefaultTableModel dtf = (DefaultTableModel) jtbEjercicios.getModel();

        int confirmado = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de que desea borrar?");

        if (fila == -1) {

            JOptionPane.showMessageDialog(rootPane, "Seleccione una fila para borrar");
        }

        if (JOptionPane.YES_OPTION == confirmado) {

            detalleRutina.borrarDetallesRutina(jtbEjercicios.getValueAt(fila, 0).toString());

            dtf.removeRow(fila);
            JOptionPane.showMessageDialog(rootPane, "se ha borrado con exito");

        }
        if (JOptionPane.NO_OPTION == confirmado) {

            JOptionPane.showMessageDialog(rootPane, " NO se ha borrado ");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtFecha_Inicio.getText()) || txtFecha_Final.getText()=="" ) {
            
           
                JOptionPane.showMessageDialog(rootPane, "Establezca fechas");
            
        }else{
            
        
        if (esInsercion == true) {
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date(txtFecha_Inicio.getText());
            Date date1 = new Date(txtFecha_Final.getText());

            detalle.insertarDetallesRutina(txtId_Rutina.getText(),
                    dateFormat.format(date), dateFormat.format(date1));

        } else {
            String fechaInicio = txtFecha_Inicio.getText();
            String aux[] = fechaInicio.split("-");
            fechaInicio = aux[2] + "-" + aux[1] + "-" + aux[0];
            String fechaFin = txtFecha_Final.getText();
            aux = fechaFin.split("-");
            fechaFin = aux[2] + "-" + aux[1] + "-" + aux[0];

            detalle.actualizarRutinas(fechaInicio, fechaFin, txtId_cliente.getText());
            rutinap.actualizarFechas(fechaInicio, fechaFin);
        }
        rutinap.LimpiarTabla();
        rutinap.rellenarDatosTabla(txtId_cliente.getText());

        dispose();

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Rutinas dialog = new Rutinas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbEjercicios;
    private javax.swing.JLabel lblFecha_Final;
    private javax.swing.JLabel lblFecha_Inicio;
    private javax.swing.JLabel lblId_Rutina;
    private javax.swing.JTextField txtFecha_Final;
    private javax.swing.JTextField txtFecha_Inicio;
    private javax.swing.JTextField txtId_Rutina;
    private javax.swing.JTextField txtId_cliente;
    // End of variables declaration//GEN-END:variables

    public void establecerFechas(String fechaInicio, String fechaFinal) {
        this.txtFecha_Inicio.setText(fechaInicio);
        this.txtFecha_Final.setText(fechaFinal);
    }

}
